// =========================================
// SERVER-SIDE PDF GENERATOR — Propuesta Comercial Platomico
// server-only
//
// Architecture:
//   1. Pages 1–10  → from /public/Sales Deck.pdf as-is
//      (Page 1 gets brand_name overlay via pdf-lib)
//   2. Page 11     → generated by Puppeteer (Propuesta Comercial)
//   3. Page 12     → from /public/Sales Deck.pdf as-is
//
// renderHtmlToPdf is kept as a shared utility used by invoice.ts / presupuesto.ts.
// =========================================

import fs from 'fs'
import path from 'path'
import { PDFDocument, StandardFonts, rgb } from 'pdf-lib'
import type { Deal, DealConfiguration, DealEconomics, ProposalSections, DeliveryPlanId } from '@/types'
import { PLANS, ADDONS, HARDWARE, RENTAL_MONTHLY_PRICE, DELIVERY_PLANS } from '@/lib/pricing/catalog'
import { calculateMonthlyTotals } from '@/lib/pricing/totals'

// ── Logo ──────────────────────────────────────────────────────────────────────

function readLogoDataUri(): string {
  for (const { file, mime } of [
    { file: 'logo_platomico.png', mime: 'image/png' },
    { file: 'logo_platomico.svg', mime: 'image/svg+xml' },
  ]) {
    try {
      const buf = fs.readFileSync(path.join(process.cwd(), 'public', file))
      return `data:${mime};base64,${buf.toString('base64')}`
    } catch { /* continuar */ }
  }
  return ''
}

// ── Timeouts ──────────────────────────────────────────────────────────────────
const SET_CONTENT_MS = 15_000
const PDF_RENDER_MS  = 45_000

function withTimeout<T>(p: Promise<T>, ms: number, label: string): Promise<T> {
  return Promise.race([
    p,
    new Promise<never>((_, rej) =>
      setTimeout(() => rej(new Error(`PDF timeout: ${label} (>${ms}ms)`)), ms)
    ),
  ])
}

// ── Shared Puppeteer launcher ─────────────────────────────────────────────────
async function launchBrowser(viewportW: number, viewportH: number) {
  const puppeteer = (await import('puppeteer-core')).default
  const chromium  = (await import('@sparticuz/chromium')).default
  const executablePath =
    process.env.CHROME_EXECUTABLE_PATH ?? (await chromium.executablePath())
  return puppeteer.launch({
    args: [...chromium.args, '--disable-dev-shm-usage', '--no-zygote'],
    defaultViewport: { width: viewportW, height: viewportH },
    executablePath,
    headless: true,
  })
}

// ── renderHtmlToPdf — multi-page A4 portrait (used by invoice.ts, presupuesto.ts) ──
export async function renderHtmlToPdf(html: string): Promise<Buffer> {
  const browser = await launchBrowser(1240, 1754)
  try {
    const page = await browser.newPage()
    await withTimeout(
      page.setContent(html, { waitUntil: 'domcontentloaded' }),
      SET_CONTENT_MS, 'setContent'
    )
    const pdf = await withTimeout(page.pdf({
      format: 'A4',
      printBackground: true,
      displayHeaderFooter: true,
      headerTemplate: `<div style="font-size:1px;"> </div>`,
      footerTemplate: `
        <div style="
          width:100%; padding:3px 14mm;
          display:flex; align-items:center; justify-content:space-between;
          border-top:1px solid #dde6f0; box-sizing:border-box;
          font-family:Helvetica,Arial,sans-serif;
        ">
          <span style="font-size:7px; color:#94a3b8;">
            Platomico, S.L. · NIF B22741094 · Calle Antonio Machado 9, Rozas de Puerto Real, Madrid 28649 · hola@platomico.com
          </span>
          <span style="font-size:7px; color:#94a3b8; white-space:nowrap; margin-left:8px;">
            Pág. <span class="pageNumber"></span>
          </span>
        </div>`,
      margin: { top: '12mm', bottom: '14mm', left: '14mm', right: '14mm' },
    }), PDF_RENDER_MS, 'page.pdf')
    return Buffer.from(pdf)
  } finally {
    await browser.close()
  }
}

// ── renderSlidePdf — single slide at fixed CSS pixel dimensions ───────────────
async function renderSlidePdf(html: string, cssW: number, cssH: number): Promise<Buffer> {
  const browser = await launchBrowser(cssW, cssH)
  try {
    const page = await browser.newPage()
    await page.setViewport({ width: cssW, height: cssH })
    await withTimeout(
      page.setContent(html, { waitUntil: 'domcontentloaded' }),
      SET_CONTENT_MS, 'setContent'
    )
    const pdf = await withTimeout(page.pdf({
      width: `${cssW}px`,
      height: `${cssH}px`,
      printBackground: true,
      margin: { top: 0, right: 0, bottom: 0, left: 0 },
    }), PDF_RENDER_MS, 'page.pdf')
    return Buffer.from(pdf)
  } finally {
    await browser.close()
  }
}

// ── Formatters ────────────────────────────────────────────────────────────────
function fmt(n: number): string {
  return n.toLocaleString('es-ES', {
    style: 'currency', currency: 'EUR',
    minimumFractionDigits: 2, maximumFractionDigits: 2,
  })
}

function esc(s: string): string {
  return s
    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

function fmtN(n: number): string { return n.toLocaleString('es-ES') }

// ── Line-item computation ─────────────────────────────────────────────────────

interface LineItem {
  concept: string
  qty: string
  unitPrice: string
  total: number
  note?: string
  isNegative?: boolean
  isOneTime?: boolean
}

function buildLineItems(cfg: DealConfiguration): { items: LineItem[]; baseImponible: number } {
  const eco = cfg.economics as DealEconomics & {
    renEnabled?: boolean
    renFeePerOrder?: number
    renVenues?: number
    discountPercent?: number
    discountName?: string
    kdsVenues?: number
    kioskVenues?: number
    deliveryPlanKey?: string
    deliveryPlan?: string
    deliveryFixedFee?: number
    datafonoFeeMonthly?: number
    hardwareRevenueMonthly?: number
  }

  const plan           = PLANS[cfg.plan]
  const deliveryPlanId = (eco.deliveryPlanKey ?? eco.deliveryPlan ?? 'start') as DeliveryPlanId
  const kdsVenues      = eco.kdsVenues    ?? cfg.locations
  const kioskVenues    = eco.kioskVenues  ?? cfg.locations

  const totals = calculateMonthlyTotals({
    economics: eco,
    locations: cfg.locations,
    activeAddons: cfg.activeAddons,
    deliveryPlan: deliveryPlanId,
    deliveryFixedFeePerLoc: eco.deliveryFixedFee,
    kdsVenues,
    kioskVenues,
  })

  const items: LineItem[] = []

  // 1. Plan fee
  const planFixedFee = Math.ceil(plan.priceMonthly * cfg.locations)
  if (planFixedFee > 0) {
    items.push({
      concept: `ROS ${plan.label} — licencia mensual`,
      qty: `${cfg.locations} local${cfg.locations !== 1 ? 'es' : ''}`,
      unitPrice: `${fmt(plan.priceMonthly)}/local`,
      total: planFixedFee,
    })
  }

  // 2. Active add-ons
  for (const addonId of cfg.activeAddons) {
    const addon = ADDONS[addonId]
    if (addonId === 'delivery_integrations') {
      if (totals.deliveryFee > 0) {
        const dpLabel = DELIVERY_PLANS[deliveryPlanId]?.label ?? deliveryPlanId
        items.push({
          concept: `Delivery — integración (${dpLabel})`,
          qty: `${cfg.locations} local${cfg.locations !== 1 ? 'es' : ''}`,
          unitPrice: eco.deliveryFixedFee
            ? `${fmt(eco.deliveryFixedFee)}/local`
            : fmt(totals.deliveryFee),
          total: totals.deliveryFee,
          note: '+ tarifa variable por pedido adicional',
        })
      }
    } else if (addonId === 'kds') {
      const unit = ADDONS['kds'].priceMonthly ?? 19
      items.push({
        concept: 'KDS — Kitchen Display',
        qty: `${kdsVenues} local${kdsVenues !== 1 ? 'es' : ''}`,
        unitPrice: `${fmt(unit)}/local`,
        total: unit * kdsVenues,
      })
    } else if (addonId === 'kiosk') {
      const unit = ADDONS['kiosk'].priceMonthly ?? 19
      items.push({
        concept: 'Kiosk — Self-ordering',
        qty: `${kioskVenues} local${kioskVenues !== 1 ? 'es' : ''}`,
        unitPrice: `${fmt(unit)}/local`,
        total: unit * kioskVenues,
      })
    } else if (addonId === 'datafono') {
      items.push({
        concept: 'Datáfono integrado',
        qty: '—',
        unitPrice: `${addon.feePercent}% GMV`,
        total: totals.datafonoFee,
        note: 'Coste variable según GMV mensual',
      })
    } else if (addon.priceMonthly != null) {
      const qty = addon.perLocation ? cfg.locations : 1
      items.push({
        concept: addon.label,
        qty: addon.perLocation ? `${qty} local${qty !== 1 ? 'es' : ''}` : '1',
        unitPrice: `${fmt(addon.priceMonthly)}${addon.perLocation ? '/local' : '/mes'}`,
        total: addon.priceMonthly * qty,
      })
    }
  }

  // 3. Hardware
  for (const item of cfg.hardware.filter(h => h.quantity > 0)) {
    const hw = HARDWARE[item.hardwareId]
    if (item.mode === 'included') continue
    const lineTotal = item.unitPrice * item.quantity
    if (item.mode === 'sold') {
      items.push({
        concept: hw.label,
        qty: `${item.quantity} ud.`,
        unitPrice: fmt(item.unitPrice),
        total: lineTotal,
        isOneTime: true,
      })
    } else {
      const rentalUnit = hw.rentalMonthlyPrice ?? RENTAL_MONTHLY_PRICE
      const monthly = item.mode === 'financed' && item.financeMonths
        ? Math.ceil(lineTotal / item.financeMonths)
        : rentalUnit * item.quantity
      const modeLabel = item.mode === 'rented'
        ? 'alquiler'
        : `financiado ${item.financeMonths} meses`
      items.push({
        concept: `${hw.label} (${modeLabel})`,
        qty: `${item.quantity} ud.`,
        unitPrice: item.mode === 'rented'
          ? `${fmt(rentalUnit)}/ud./mes`
          : `${fmt(Math.ceil(lineTotal / (item.financeMonths ?? 1)))}/mes`,
        total: monthly,
      })
    }
  }

  // 4. REN estimate
  if (eco.renEnabled === true) {
    const rfpo = eco.renFeePerOrder ?? 0.10
    const rv   = eco.renVenues ?? 1
    const dpv  = cfg.deliveryOrdersPerVenue ?? 0
    const renMonthly = rfpo * dpv * rv
    if (renMonthly > 0) {
      items.push({
        concept: 'REN — Logística propia (estimado)',
        qty: `${fmtN(dpv * rv)} pedidos/mes est.`,
        unitPrice: `${rfpo.toFixed(2).replace('.', ',')} €/pedido`,
        total: renMonthly,
        note: 'Variable · liquidado a mes vencido',
      })
    }
  }

  // 5. Discount
  const discountPercent = eco.discountPercent ?? 0
  if (discountPercent > 0) {
    const softwareBase = planFixedFee + totals.addonFee + totals.datafonoFee
    const discountAmount = softwareBase * (discountPercent / 100)
    items.push({
      concept: eco.discountName ? `Descuento — ${eco.discountName}` : `Descuento ${discountPercent}%`,
      qty: `−${discountPercent}%`,
      unitPrice: '—',
      total: -discountAmount,
      isNegative: true,
    })
  }

  // Base imponible = all recurring monthly items net of discount
  const discountBase   = planFixedFee + totals.addonFee + totals.datafonoFee
  const discountAmount = discountBase * (discountPercent / 100)
  const hwMonthly      = (eco.hardwareRevenueMonthly as number | undefined) ?? 0
  const renFinal = eco.renEnabled === true
    ? (eco.renFeePerOrder ?? 0.10) * (cfg.deliveryOrdersPerVenue ?? 0) * (eco.renVenues ?? 1)
    : 0
  const baseImponible =
    planFixedFee + totals.addonFee + totals.datafonoFee +
    totals.deliveryFee + hwMonthly + renFinal - discountAmount

  return { items, baseImponible }
}

// ── Page 11 HTML — Propuesta Comercial ───────────────────────────────────────
// Dimensions: A4 landscape rendered at 1123×794 CSS px → 841.89×595.28 pt
// Style: background #F5F4F0, accent #4B5EFF, Inter font

const A4L_CSS_W = 1123
const A4L_CSS_H = 794

function buildProposalPageHtml(deal: Deal, cfg: DealConfiguration, logoUri: string): string {
  const { items, baseImponible } = buildLineItems(cfg)
  const ivaAmount  = baseImponible * 0.21
  const totalOferta = baseImponible * 1.21
  const brandName  = deal.company.brandName ?? deal.company.name
  const clientCif  = deal.company.cif ? `NIF/CIF: ${esc(deal.company.cif)}` : ''
  const clientAddr = [deal.company.address, deal.company.city].filter((s): s is string => Boolean(s)).map(esc).join(', ')

  const rowsHtml = items.map((item, i) => {
    const bg = i % 2 === 0 ? '#FFFFFF' : '#EDECEA'
    const totalColor = item.isNegative ? '#dc2626' : '#1a1a2e'
    const totalStr = item.isNegative
      ? `−${fmt(Math.abs(item.total))}`
      : item.isOneTime
        ? `${fmt(item.total)} <span style="font-size:0.7vh;color:#9ca3af;">(único)</span>`
        : `${fmt(item.total)}/mes`
    return `
      <tr style="background:${bg};">
        <td style="padding:0.85vh 1.1vw;font-size:1.08vh;color:#1a1a2e;line-height:1.4;">
          ${esc(item.concept)}
          ${item.note ? `<div style="font-size:0.8vh;color:#9ca3af;margin-top:0.15vh;">${esc(item.note)}</div>` : ''}
        </td>
        <td style="padding:0.85vh 1.1vw;font-size:1.08vh;color:#6b7280;text-align:right;white-space:nowrap;">${esc(item.qty)}</td>
        <td style="padding:0.85vh 1.1vw;font-size:1.08vh;color:#6b7280;text-align:right;white-space:nowrap;">${item.unitPrice}</td>
        <td style="padding:0.85vh 1.1vw;font-size:1.08vh;color:${totalColor};font-weight:600;text-align:right;white-space:nowrap;">${totalStr}</td>
      </tr>`
  }).join('')

  const logoHtml = logoUri
    ? `<img src="${logoUri}" style="height:3vh;width:auto;" alt="Platomico"/>`
    : `<span style="font-size:1.5vh;font-weight:800;color:#1a1a2e;">Platomico.</span>`

  return `<!DOCTYPE html>
<html lang="es">
<head>
<meta charset="UTF-8"/>
<style>
  @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap');
  *, *::before, *::after { margin:0; padding:0; box-sizing:border-box; }
  html, body {
    width: ${A4L_CSS_W}px;
    height: ${A4L_CSS_H}px;
    overflow: hidden;
    font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
    background: #F5F4F0;
    color: #1a1a2e;
    -webkit-print-color-adjust: exact;
    print-color-adjust: exact;
  }
  .slide {
    width: ${A4L_CSS_W}px;
    height: ${A4L_CSS_H}px;
    background: #F5F4F0;
    display: flex;
    flex-direction: column;
    padding: 3.2vh 3vw;
  }
  /* Header */
  .header {
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding-bottom: 1.6vh;
    margin-bottom: 2vh;
    border-bottom: 2.5px solid #4B5EFF;
    flex-shrink: 0;
  }
  .title {
    font-size: 3vh;
    font-weight: 800;
    color: #1a1a2e;
    letter-spacing: -0.03em;
  }
  /* Parties */
  .parties {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 1.4vw;
    margin-bottom: 1.8vh;
    flex-shrink: 0;
  }
  .party {
    background: #EAEAE6;
    border-radius: 4px;
    padding: 1.2vh 1.2vw;
  }
  .party-label {
    font-size: 0.72vh;
    font-weight: 700;
    text-transform: uppercase;
    letter-spacing: 2px;
    color: #9ca3af;
    margin-bottom: 0.45vh;
  }
  .party-name  { font-size: 1.25vh; font-weight: 700; color: #1a1a2e; margin-bottom: 0.3vh; }
  .party-detail { font-size: 0.95vh; color: #6b7280; line-height: 1.5; }
  /* Table */
  .table-wrap { flex: 1; min-height: 0; overflow: hidden; margin-bottom: 1.8vh; }
  table { width: 100%; border-collapse: collapse; }
  thead tr { background: #4B5EFF; }
  thead th {
    padding: 0.8vh 1.1vw;
    font-size: 0.75vh;
    font-weight: 700;
    letter-spacing: 1.5px;
    text-transform: uppercase;
    color: rgba(255,255,255,0.85);
    text-align: left;
  }
  thead th.r { text-align: right; }
  /* Totals */
  .totals-row { display: flex; justify-content: flex-end; flex-shrink: 0; }
  .totals-box {
    width: 28vw;
    background: #fff;
    border: 1.5px solid #E0DED9;
    border-radius: 4px;
    overflow: hidden;
  }
  .tot-line {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 0.8vh 1.1vw;
    font-size: 1.05vh;
    border-bottom: 1px solid #F0EEE9;
  }
  .tot-line .lbl { color: #6b7280; }
  .tot-line .val { font-weight: 600; color: #1a1a2e; }
  .tot-final {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 1vh 1.1vw;
    background: #4B5EFF;
  }
  .tot-final .lbl {
    font-size: 0.75vh;
    font-weight: 700;
    letter-spacing: 1.5px;
    text-transform: uppercase;
    color: rgba(255,255,255,0.75);
  }
  .tot-final .val { font-size: 1.5vh; font-weight: 700; color: #fff; }
</style>
</head>
<body>
<div class="slide">

  <div class="header">
    ${logoHtml}
    <div class="title">Propuesta Platomico.</div>
  </div>

  <div class="parties">
    <div class="party">
      <div class="party-label">Emisor</div>
      <div class="party-name">Platomico, S.L.</div>
      <div class="party-detail">NIF: B22741094<br/>C/ Antonio Machado, 9. Rozas de Puerto Real, Madrid. 28649.</div>
    </div>
    <div class="party">
      <div class="party-label">Destinatario</div>
      <div class="party-name">${esc(brandName)}</div>
      <div class="party-detail">
        ${clientCif ? `${clientCif}<br/>` : ''}${clientAddr}
      </div>
    </div>
  </div>

  <div class="table-wrap">
    <table>
      <thead>
        <tr>
          <th>Concepto</th>
          <th class="r" style="width:15vw;">Cantidad</th>
          <th class="r" style="width:13vw;">Precio unit.</th>
          <th class="r" style="width:14vw;">Importe</th>
        </tr>
      </thead>
      <tbody>
        ${rowsHtml || `<tr><td colspan="4" style="padding:1vh;font-size:1.05vh;color:#9ca3af;text-align:center;">Sin partidas configuradas</td></tr>`}
      </tbody>
    </table>
  </div>

  <div class="totals-row">
    <div class="totals-box">
      <div class="tot-line">
        <span class="lbl">Base imponible</span>
        <span class="val">${fmt(baseImponible)}</span>
      </div>
      <div class="tot-line">
        <span class="lbl">IVA (21%)</span>
        <span class="val">${fmt(ivaAmount)}</span>
      </div>
      <div class="tot-final">
        <span class="lbl">Total Oferta</span>
        <span class="val">${fmt(totalOferta)}</span>
      </div>
    </div>
  </div>

</div>
</body>
</html>`
}

// ── Entry point ───────────────────────────────────────────────────────────────
export async function generateProposalPdf(
  deal: Deal,
  cfg: DealConfiguration,
  _sections: ProposalSections
): Promise<Buffer> {
  const deckPath  = path.join(process.cwd(), 'public', 'Sales Deck.pdf')
  const deckBytes = fs.readFileSync(deckPath)
  const deckDoc   = await PDFDocument.load(deckBytes)

  // ── 1. Copy deck pages 1–10 (indices 0–9) ──────────────────────────────────
  const outDoc = await PDFDocument.create()
  const first10 = await outDoc.copyPages(deckDoc, [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
  first10.forEach(p => outDoc.addPage(p))

  // ── 2. Overlay brand_name on cover page (index 0) ──────────────────────────
  const brandName = deal.company.brandName ?? deal.company.name
  if (brandName) {
    const coverPage = outDoc.getPages()[0]
    const helvetica = await outDoc.embedFont(StandardFonts.Helvetica)
    coverPage.drawText(brandName, {
      x: 80,
      y: 60,
      size: 18,
      font: helvetica,
      color: rgb(1, 1, 1),
    })
  }

  // ── 3. Generate page 11 with Puppeteer ─────────────────────────────────────
  const logoUri    = readLogoDataUri()
  const html       = buildProposalPageHtml(deal, cfg, logoUri)
  const slidePdfBuf = await renderSlidePdf(html, A4L_CSS_W, A4L_CSS_H)
  const slideDoc   = await PDFDocument.load(slidePdfBuf)
  const [slidePage] = await outDoc.copyPages(slideDoc, [0])
  outDoc.addPage(slidePage)

  // ── 4. Copy deck page 12 (index 11) ────────────────────────────────────────
  const [deckPage12] = await outDoc.copyPages(deckDoc, [11])
  outDoc.addPage(deckPage12)

  const outBytes = await outDoc.save()
  return Buffer.from(outBytes)
}
